#!/usr/bin/env python

"""
creates local cache of instance tiddlers to be included in distribution
"""

import sys

import mangler # XXX: DEBUG
from tiddlywebplugins.instancer.util import cache_tiddlers


def main(args):
	cache_tiddlers("tiddlywebwiki")
	return True


if __name__ == "__main__":
	status = not main(sys.argv)
	sys.exit(status)
