#!/usr/bin/env python

"""
creates a TiddlyWebWiki instance

comfort wrapper for twanager --load tiddlywebwiki.config instance
"""

import sys

import tiddlywebwiki

from tiddlyweb.config import config


def main(args=None):
	args = [unicode(arg, "UTF-8") for arg in args]
	try:
		instance_path = args[1]
	except IndexError:
		prompt = "Please enter instance name or path:\n"
		instance_path = raw_input(prompt)
	tiddlywebwiki.init(config)
	tiddlywebwiki.instancer.instance(instance_path)
	return True


if __name__ == "__main__":
	status = not main(sys.argv)
	sys.exit(status)
